server:
  port: 8080

gateway:
  rate-limit:
    requests-per-second: ${GATEWAY_RATE_LIMIT_PER_SECOND:10}

spring:
  cloud:
    gateway:
      routes:
        - id: orchestration-api
          uri: ${ORCH_SERVICE_URL:http://cds-orch-service:8082}
          predicates:
            - Path=/api/v1/**